version: 2
updates:

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      # Check for updates to cargo dependencies every week
      interval: "weekly"
    open-pull-requests-limit: 1
    allow:
    - dependency-type: direct
    - dependency-type: indirect

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every week
      interval: "weekly"

  - package-ecosystem: docker
    directory: /container
    schedule:
      interval: daily

  - package-ecosystem: cargo
    directory: /deps/td-shim-AzCVMEmu/azcvm-extract-report
    schedule:
      interval: daily
