[package]
name = "json-signer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
crypto = { path = "../../src/crypto" }
serde_json = { version = "1.0", features = ["raw_value", "preserve_order"] }
der = "0.7"