name: Weekly Collateral Update

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  generate-collateral-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          submodules: recursive

      - name: Install rust
        uses: dtolnay/rust-toolchain@efa25f7f19611383d5b0ccf2d1c8914531636bf9 # master
        with:
          toolchain: 1.88.0

      - name: Build migtd-collateral-generator
        run: |
          pushd tools/migtd-collateral-generator
          cargo build --release
          popd

      - name: Build migtd-policy-generator
        run: |
          pushd tools/migtd-policy-generator
          cargo build --release
          popd

      - name: Generate collateral (production)
        run: ./target/release/migtd-collateral-generator -o config/collateral_production_fmspc.json

      - name: Generate collateral (pre-production)
        run: ./target/release/migtd-collateral-generator -o config/collateral_pre_production_fmspc.json --pre-production

      - name: Generate policy (production)
        run: ./target/release/migtd-policy-generator -o config/policy_production_fmspc.json

      - name: Generate policy (pre-production)
        run: ./target/release/migtd-policy-generator -o config/policy_pre_production_fmspc.json --pre-production

      - name: Create Pull Request for Collateral
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: "chore: update collateral files"
          title: "chore: update collateral files"
          body: |
            Weekly collateral update.
            Auto-generated by GitHub Actions.
          branch: update-collateral
          delete-branch: true
          add-paths: |
            config/collateral_production_fmspc.json
            config/collateral_pre_production_fmspc.json

      - name: Create Pull Request for Policy
        uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
        with:
          commit-message: "chore: update policy v1 files"
          title: "chore: update policy files"
          body: |
            Weekly policy update.
            Auto-generated by GitHub Actions.
          branch: update-policy
          delete-branch: true
          add-paths: |
            config/policy_production_fmspc.json
            config/policy_pre_production_fmspc.json
