name: Weekly Collateral Update

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC
  workflow_dispatch:

jobs:
  generate-collateral-policy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Install rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.88.0

      - name: Build migtd-collateral-generator
        run: |
          pushd tools/migtd-collateral-generator
          cargo build --release
          popd

      - name: Build migtd-policy-generator
        run: |
          pushd tools/migtd-policy-generator
          cargo build --release
          popd

      - name: Generate collateral (production)
        run: ./target/release/migtd-collateral-generator -o config/collateral_production_fmspc.json

      - name: Generate collateral (pre-production)
        run: ./target/release/migtd-collateral-generator -o config/collateral_pre_production_fmspc.json --pre-production

      - name: Generate policy (production)
        run: ./target/release/migtd-policy-generator -o config/policy_production_fmspc.json

      - name: Generate policy (pre-production)
        run: ./target/release/migtd-policy-generator -o config/policy_pre_production_fmspc.json --pre-production

      - name: Create Pull Request for Collateral
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: update collateral files"
          title: "chore: update collateral files"
          body: |
            Weekly collateral update.
            Auto-generated by GitHub Actions.
          branch: update-collateral
          delete-branch: true
          add-paths: |
            config/collateral_production_fmspc.json
            config/collateral_pre_production_fmspc.json

      - name: Create Pull Request for Policy
        uses: peter-evans/create-pull-request@v8
        with:
          commit-message: "chore: update policy v1 files"
          title: "chore: update policy files"
          body: |
            Weekly policy update.
            Auto-generated by GitHub Actions.
          branch: update-policy
          delete-branch: true
          add-paths: |
            config/policy_production_fmspc.json
            config/policy_pre_production_fmspc.json
